In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../../../Bigdata Files/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [3]:
X=df.drop("target",axis=1).values

In [4]:
y=df["target"].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [10]:
knn=KNeighborsClassifier(n_neighbors=9)
nb=GaussianNB()
sv=SVC()
lst_models=[knn,nb,sv]

In [15]:
from sklearn.metrics import classification_report,accuracy_score
for model in lst_models:
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    print(model)
    print("*"*100)
    print(accuracy_score(y_test,y_pred))
    print("*"*100)
    print(classification_report(y_test,y_pred))
    print("*"*100)
    print("*"*100)
    print()

KNeighborsClassifier(n_neighbors=9)
****************************************************************************************************
0.8311688311688312
****************************************************************************************************
              precision    recall  f1-score   support

           0       0.88      0.78      0.83       159
           1       0.79      0.89      0.84       149

    accuracy                           0.83       308
   macro avg       0.83      0.83      0.83       308
weighted avg       0.84      0.83      0.83       308

****************************************************************************************************
****************************************************************************************************

GaussianNB()
****************************************************************************************************
0.814935064935065
****************************************************************************************************
              precision    recall  f1-score   support

           0       0.88      0.74      0.81       159
           1       0.76      0.89      0.82       149

    accuracy                           0.81       308
   macro avg       0.82      0.82      0.81       308
weighted avg       0.82      0.81      0.81       308

****************************************************************************************************
****************************************************************************************************

SVC()
****************************************************************************************************
0.8896103896103896
****************************************************************************************************
              precision    recall  f1-score   support

           0       0.92      0.86      0.89       159
           1       0.86      0.92      0.89       149

    accuracy                           0.89       308
   macro avg       0.89      0.89      0.89       308
weighted avg       0.89      0.89      0.89       308

****************************************************************************************************
****************************************************************************************************